### ISSUE TITLE
Paste error with CKEDITOR : this.getChildrenContainer(...) is null

### ISSUE THREAD

**Issue by LoFromCaumont** [GrapesJS/mjml#87]
Hi,
a have a weird JS error when pasting anything (even a single character) at the EDGEs of the text.
No problem pasting INSIDE existing text.
I tried with differents versions of JQUERY and CKEDITOR. Always the same bug. I think having all required plugins for CK. An idea ?

![2018-10-19_142046](https://user-images.githubusercontent.com/44293610/47217968-7b387a00-d3aa-11e8-83d9-1afbd75e9dfb.jpg)

**Comment by jmchaves** [comment]
Hey @LoFromCaumont, I got a similiar issue when I paste a text using "Ctrl + V". This happens when you combine these the plugins: `plugins: ["grapesjs-mjml", "gjs-plugin-ckeditor"]`. The text got blank then when you click outside of the component it triggers the error: 

![error](https://user-images.githubusercontent.com/2567814/56310092-f8a23480-6118-11e9-8004-00499e213e2e.gif)

@artf, do you have any idea about it?

**Comment by LoFromCaumont** [comment]
Hey, happy to not be alone !
But no, 
i didn't worked on this project since 6 months.
I suppose you tried with the lastest versions of Jquery, CK, Grapes... ?

**Comment by jmchaves** [comment]
I was running ckeditor 4.7, I switched to `4.6.2 (Standard)` and this fixed the issue.

**Comment by LoFromCaumont** [comment]
Yeah !
I'll try this change ...one day ;-(
Results in next post...
Thanks you

**Comment by DRoet** [comment]
can anyone confirm this is still an issue?
